{{- if .Values.secrets.createPlaceholder }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecret }}
  labels:
    {{- include "gulimall.labels" . | nindent 4 }}
type: Opaque
stringData:
  rds-endpoint: {{ .Values.secrets.rdsEndpoint | quote }}
  rds-username: {{ .Values.secrets.rdsUsername | quote }}
  rds-password: {{ .Values.secrets.rdsPassword | quote }}
  rabbitmq-username: {{ .Values.infra.rabbitmq.username | quote }}
  rabbitmq-password: {{ .Values.infra.rabbitmq.password | quote }}
  order-stripe-secret-key: {{ .Values.secrets.orderStripeSecretKey | quote }}
  order-stripe-webhook-secret: {{ .Values.secrets.orderStripeWebhookSecret | quote }}
{{- end }}
